"""add incidents, responder fields, power-plant split, override note

Revision ID: a3f7c1d92e6b
Revises: d0796c9c8706
Create Date: 2026-09-27 00:00:00.000000

Part of the best-practices merge described in docs/MERGE_NOTES.md. Three
independent changes bundled into one migration since they landed together:

1. hotspots gets nearest_power_plant_* (split out from nearest_industrial_*,
   which used to be duplicated into both — see app/models/hotspot.py) and
   nearest_responder_* (new — app/ingestion/osm.py's responders layer).
2. discovered_clusters gets classification_override_note (new — see
   app/ml/serving_guards.py).
3. A new `incidents` table for the tiered escalation workflow (see
   app/models/incident.py) — deliberately no Geometry column, see that
   model's docstring for why.

NOTE (hand-written, not autogenerated): unlike the initial migration, this
one has no Geometry columns, so none of the GiST-index-collision handling
from that migration's header note applies here.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = 'a3f7c1d92e6b'
down_revision = 'd0796c9c8706'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column('hotspots', sa.Column('nearest_power_plant_distance_m', sa.Float(), nullable=True))
    op.add_column('hotspots', sa.Column('nearest_power_plant_id', sa.String(length=64), nullable=True))
    op.add_column('hotspots', sa.Column('nearest_power_plant_fuel_type', sa.String(length=32), nullable=True))
    op.add_column('hotspots', sa.Column('nearest_responder_distance_m', sa.Float(), nullable=True))
    op.add_column('hotspots', sa.Column('nearest_responder_type', sa.String(length=32), nullable=True))
    op.add_column('hotspots', sa.Column('nearest_responder_name', sa.String(length=256), nullable=True))

    op.add_column('discovered_clusters', sa.Column('classification_override_note', sa.String(), nullable=True))

    op.create_table(
        'incidents',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('cluster_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('last_escalated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('predicted_class', sa.String(length=32), nullable=False),
        sa.Column('risk_score', sa.Float(), nullable=False),
        sa.Column('risk_tier', sa.String(length=4), nullable=False),
        sa.Column('centroid_lat', sa.Float(), nullable=False),
        sa.Column('centroid_lon', sa.Float(), nullable=False),
        sa.Column('nearest_responder_distance_m', sa.Float(), nullable=True),
        sa.Column('nearest_responder_type', sa.String(length=32), nullable=True),
        sa.Column('nearest_responder_name', sa.String(length=256), nullable=True),
        sa.Column('current_tier', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=16), nullable=False),
        sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('acknowledged_by', sa.String(length=256), nullable=True),
        sa.Column('ack_token', sa.String(length=64), nullable=False),
        sa.Column('dispatch_log_json', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['cluster_id'], ['discovered_clusters.cluster_id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_incidents_cluster_id'), 'incidents', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_incidents_ack_token'), 'incidents', ['ack_token'], unique=True)


def downgrade() -> None:
    op.drop_index(op.f('ix_incidents_ack_token'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_cluster_id'), table_name='incidents')
    op.drop_table('incidents')

    op.drop_column('discovered_clusters', 'classification_override_note')

    op.drop_column('hotspots', 'nearest_responder_name')
    op.drop_column('hotspots', 'nearest_responder_type')
    op.drop_column('hotspots', 'nearest_responder_distance_m')
    op.drop_column('hotspots', 'nearest_power_plant_fuel_type')
    op.drop_column('hotspots', 'nearest_power_plant_id')
    op.drop_column('hotspots', 'nearest_power_plant_distance_m')
