"""initial schema

Revision ID: d0796c9c8706
Revises: 
Create Date: 2026-09-10 13:38:45.401786

NOTE (hand-edited after autogenerate): GeoAlchemy2's Geometry columns
default to spatial_index=True, which registers a SQLAlchemy DDL
`after_create` event that creates the GiST index automatically as part of
`CREATE TABLE`. Alembic's autogenerate doesn't know that and ALSO emits an
explicit op.create_index(...) for the same index, which fails with
"relation already exists" the moment you actually run this migration.
The two op.create_index/op.drop_index calls for idx_discovered_clusters_
centroid_geom and idx_hotspots_geom have been removed below — GeoAlchemy2
creates/drops them automatically alongside their tables. If you regenerate
this migration (or add a new geometry column later), check any new
autogenerated migration for the same pattern and strip it the same way —
see migrations/env.py's `include_object` docstring for the companion
spatial_ref_sys issue.
"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


revision = 'd0796c9c8706'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=4), nullable=False),
    sa.Column('location_lat', sa.Float(), nullable=False),
    sa.Column('location_lon', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('cluster_ids_involved', sa.JSON(), nullable=False),
    sa.Column('edge_id', sa.Integer(), nullable=True),
    sa.Column('sachet_payload', sa.JSON(), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discovered_clusters',
    sa.Column('cluster_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('centroid_lat', sa.Float(), nullable=False),
    sa.Column('centroid_lon', sa.Float(), nullable=False),
    sa.Column('centroid_geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_detections', sa.Integer(), nullable=False),
    sa.Column('predicted_class', sa.String(length=32), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('top_reasons_json', sa.String(), nullable=True),
    sa.Column('chem_fingerprint_score', sa.Float(), nullable=True),
    sa.Column('sar_structural_change_score', sa.Float(), nullable=True),
    sa.Column('gfm_novelty_score', sa.Float(), nullable=True),
    sa.Column('centrality_score', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_tier', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('cluster_id')
    )
    op.create_index(op.f('ix_discovered_clusters_predicted_class'), 'discovered_clusters', ['predicted_class'], unique=False)
    op.create_table('anomaly_flags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('sensor', sa.String(length=32), nullable=False),
    sa.Column('flag_type', sa.String(length=8), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity_score', sa.Float(), nullable=False),
    sa.Column('baseline_value', sa.Float(), nullable=True),
    sa.Column('observed_value', sa.Float(), nullable=True),
    sa.Column('frp_trend', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['discovered_clusters.cluster_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_flags_cluster_id'), 'anomaly_flags', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_anomaly_flags_timestamp'), 'anomaly_flags', ['timestamp'], unique=False)
    op.create_table('cluster_edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_cluster_id', sa.Integer(), nullable=False),
    sa.Column('target_cluster_id', sa.Integer(), nullable=False),
    sa.Column('edge_type', sa.String(length=16), nullable=False),
    sa.Column('connection_detail', sa.String(length=64), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['source_cluster_id'], ['discovered_clusters.cluster_id'], ),
    sa.ForeignKeyConstraint(['target_cluster_id'], ['discovered_clusters.cluster_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cluster_edges_source_cluster_id'), 'cluster_edges', ['source_cluster_id'], unique=False)
    op.create_index(op.f('ix_cluster_edges_target_cluster_id'), 'cluster_edges', ['target_cluster_id'], unique=False)
    op.create_table('hotspots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('acq_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sensor', sa.String(length=32), nullable=False),
    sa.Column('frp', sa.Float(), nullable=True),
    sa.Column('brightness_temp', sa.Float(), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=True),
    sa.Column('daynight', sa.String(length=1), nullable=True),
    sa.Column('land_cover_class', sa.Integer(), nullable=True),
    sa.Column('nearest_industrial_distance_m', sa.Float(), nullable=True),
    sa.Column('nearest_industrial_id', sa.String(length=64), nullable=True),
    sa.Column('population_density_nearby', sa.Float(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['discovered_clusters.cluster_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotspots_acq_datetime'), 'hotspots', ['acq_datetime'], unique=False)
    op.create_index(op.f('ix_hotspots_cluster_id'), 'hotspots', ['cluster_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hotspots_cluster_id'), table_name='hotspots')
    op.drop_index(op.f('ix_hotspots_acq_datetime'), table_name='hotspots')
    op.drop_table('hotspots')
    op.drop_index(op.f('ix_cluster_edges_target_cluster_id'), table_name='cluster_edges')
    op.drop_index(op.f('ix_cluster_edges_source_cluster_id'), table_name='cluster_edges')
    op.drop_table('cluster_edges')
    op.drop_index(op.f('ix_anomaly_flags_timestamp'), table_name='anomaly_flags')
    op.drop_index(op.f('ix_anomaly_flags_cluster_id'), table_name='anomaly_flags')
    op.drop_table('anomaly_flags')
    op.drop_index(op.f('ix_discovered_clusters_predicted_class'), table_name='discovered_clusters')
    op.drop_table('discovered_clusters')
    op.drop_table('alerts')
    # ### end Alembic commands ###
